### ISSUE TITLE
Set static serving dir to a separate directory

### ISSUE THREAD

**Issue by rstrom1763** [rstrom1763/AF-NCC-Scripts#17]
Instead of using the main directory of "api" to serve the static files from, create a "static" folder and server the files from there. This will make it so that client machines will only have access to the static files as intended.

**Comment by ghost** [comment]
Hi. I would like to take a crack at this issue. It would be my first one so please let me know if i'm making any mistakes. As I've understood I would have to do the following:

* move the `index.html`, `app.cs`,  and `fire.png` to a new directory called `static`
* change the locations correspondingly in `app.js` and `index.html`

Also, what is the procedure I should follow in trying to fix this issue? I would really appreciate it if you could help me out with the whole process.

**Comment by rstrom1763** [comment]
@VisakhChekur  You've got it exactly!! Just relocate all of those files to a new "static" directory and then adjust the values in the corresponding files you listed. As for contribution procedures, you can just fork the repository and make your pull request to the development branch. I make all commits on the dev branch and then pull it over to the main branch once everything is 100% stable. If you need any assistance, I'd be happy to help!

**Comment by ghost** [comment]
@rstrom1763 Sorry for the delay. So how do I go about making the pull request? From what I understand I should fork this repo, create a new branch and then make the changes and then submit a PR. Is this process correct?

**Comment by rstrom1763** [comment]
You're correct! You don't have to make another branch on your fork if you don't want to, that part is up to your own discretion. Once you make the fork you can clone it to your computer, commit changes to it, then submit a pull request which I will review before merging.

**Comment by rstrom1763** [comment]
Implemented in pull request listed below. 

https://github.com/rstrom1763/AF-NCC-Scripts/commit/034ba29120fdd5ff81c5963a3f991ceb179c126b
